package rj.hive.enums;

public enum URLType 
{
	REGISTER, LOGIN, FETCHDATE, FETCH_PRODUCT, FETCHDATEANDPRODUCT,ADD_PRODUCT,LOGOUT, FETCHUSERADDRESS, FETCHUSERADDRESSANDSET, UPDATEMAININFO, UPDATEPASSWORD, UPDATEADDRESSINFO
}